#!/usr/bin/env python3
"""Create the manually checked publication-level process/phase ledger.

Only full-text statements checked in the uploaded PDF corpus are included.
The ledger deliberately distinguishes publication-level evidence from
record-level mappings so that unresolved state/composition assignments cannot
silently enter modelling.
"""

from __future__ import annotations

import re
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "references" / "development_sources_42.csv"
OUT = ROOT / "results" / "processing_phase_extension" / "verified_publication_annotations.csv"


ANNOTATIONS = {
    1: dict(process_route="arc_melting+drop_casting", thermal_state_scope="as_cast", phase_class="single_phase_hcp", product_form="drop_cast_rod", evidence_pages="2, 7-8", evidence_summary="The alloys were arc melted under Ar and drop cast into a cylindrical copper mould; XRD identifies the full Sc series as single-phase HCP.", record_mapping_status="all_records_direct"),
    2: dict(process_route="arc_melting+induction_melt_spinning", thermal_state_scope="as_cast_ingot_or_melt_spun_ribbon", phase_class="single_phase_hcp", product_form="ingot_or_ribbon", evidence_pages="2, 6", evidence_summary="The paper reports an arc-melted ingot and a ribbon ejected onto a Cu wheel at 25 m s-1; both are single-phase HCP and their measured compositions identify the two records.", record_mapping_status="record_states_restored"),
    3: dict(process_route="melt_extraction", thermal_state_scope="as_extracted", phase_class="amorphous", product_form="microwire", evidence_pages="1-2", evidence_summary="The study states that the microwires were fabricated by melt extraction; XRD/DSC confirm an amorphous structure.", record_mapping_status="all_records_direct"),
    4: dict(process_route="arc_melting", thermal_state_scope="as_cast", phase_class="single_phase_hcp", product_form="ingot", evidence_pages="2-4", evidence_summary="The alloys were arc melted under high-purity Ar and examined in the as-cast state; the rare-earth additions retain the HCP structure.", record_mapping_status="all_records_direct"),
    5: dict(process_route="arc_melting+drop_casting", thermal_state_scope="as_cast", phase_class="composition_dependent_hcp_trigonal", product_form="drop_cast_rod", evidence_pages="2-4", evidence_summary="Arc-melted alloys were drop cast into a Cu mould. The quinary alloy is single HCP, whereas the four- and three-component alloys contain HCP and trigonal phases.", record_mapping_status="composition_rule_required"),
    6: dict(process_route="arc_melting+melt_spinning", thermal_state_scope="as_spun", phase_class="single_phase_amorphous", product_form="ribbon", evidence_pages="2", evidence_summary="The ingot was arc melted and injected onto a spinning Cu roller; XRD shows a fully amorphous microstructure.", record_mapping_status="all_records_direct"),
    7: dict(process_route="arc_melting+suction_casting", thermal_state_scope="as_cast", phase_class="amorphous", product_form="rod", evidence_pages="2-3", evidence_summary="Arc-melted ingots were suction cast into 1 mm Cu-mould rods; XRD shows no crystalline peaks and confirms a fully amorphous structure.", record_mapping_status="all_records_direct"),
    8: dict(process_route="arc_melting+melt_spinning_or_suction_casting", thermal_state_scope="as_cast", phase_class="amorphous", product_form="ribbon_or_rod", evidence_pages="2-4", evidence_summary="Arc-melted master alloys were melt spun as ribbons; the rare-earth-substituted compositions were also suction cast as rods. All reported products are amorphous, but the TC record-to-product mapping is not explicit.", record_mapping_status="product_form_mapping_required"),
    9: dict(process_route="arc_melting+melt_spinning", thermal_state_scope="as_spun", phase_class="amorphous", product_form="ribbon", evidence_pages="2", evidence_summary="Arc-melted ingots were remelted and injected onto a Cu roller; XRD confirms amorphous ribbons, and the reported TC values are assigned by composition.", record_mapping_status="all_records_direct"),
    10: dict(process_route="arc_melting+copper_mold_casting", thermal_state_scope="as_cast", phase_class="amorphous", product_form="bulk_metallic_glass", evidence_pages="2", evidence_summary="Master alloys were arc melted and copper-mould cast; the amorphous nature of the as-cast samples was checked by XRD.", record_mapping_status="all_records_direct"),
    11: dict(process_route="arc_melting+suction_casting+melt_extraction", thermal_state_scope="as_cast_or_current_annealed", phase_class="amorphous_nanocrystalline", product_form="microwire", evidence_pages="2-8", evidence_summary="Melt-extracted microwires were current annealed at 50, 75, or 100 x 10^6 A m-2 for 480 s in air, producing amorphous/nanocrystalline states.", record_mapping_status="record_states_restored"),
    12: dict(process_route="arc_melting", thermal_state_scope="as_cast", phase_class="two_ccp_solid_solutions_plus_sigma", product_form="ingot", evidence_pages="2-5", evidence_summary="The as-cast alloy was arc melted. XRD/SEM identify a principal ccp phase, a Cu-rich ccp phase and a sigma-type V-rich intermetallic.", record_mapping_status="all_records_direct"),
    13: dict(process_route="arc_melting+vacuum_annealing+water_quenching", thermal_state_scope="annealed_1023K_72h_vacuum_water_quenched", phase_class="composition_dependent_hexagonal_orthorhombic", product_form="ingot", evidence_pages="2-5", evidence_summary="Arc-melted alloys were annealed at 1023 K for 72 h in evacuated quartz and water quenched. The first series is Ni2In-type hexagonal; the second evolves between hexagonal and hexagonal+orthorhombic states.", record_mapping_status="composition_rule_required"),
    14: dict(process_route="arc_melting+copper_mold_casting+ball_milling+annealing_or_hydrogenation", thermal_state_scope="annealed_538K_150ks_or_hydrogenated_538K_5MPa_150ks", phase_class="state_dependent_amorphous_nanocrystalline_or_dihydride", product_form="powder", evidence_pages="2-5", evidence_summary="Copper-mould-cast glass was ball milled. Hydrogen-free powder was annealed at 538 K for 150 ks; the comparison powder was hydrogenated at 538 K and 5 MPa H2 for 150 ks, producing nanocrystalline dihydrides.", record_mapping_status="record_states_restored"),
    15: dict(process_route="arc_melting+melt_spinning", thermal_state_scope="as_spun", phase_class="single_phase_fcc", product_form="melt_spun_flakes", evidence_pages="2-4", evidence_summary="Arc-melted ingots were melt spun at 40 m s-1, producing brittle crystalline flakes; XRD identifies a single FCC solid solution across the series.", record_mapping_status="all_records_direct"),
    16: dict(process_route="arc_melting", thermal_state_scope="as_cast", phase_class="hcp_with_sem_detected_minority_phase", product_form="ingot", evidence_pages="2-4", evidence_summary="Room-temperature XRD is indexed as HCP, while SEM-EDX reveals a Si-depleted minority phase not resolved as a distinct XRD phase.", record_mapping_status="all_records_direct"),
    17: dict(process_route="arc_melting+annealing+water_quenching", thermal_state_scope="annealed_1123K_30min_water_quenched", phase_class="single_phase_fcc", product_form="ingot", evidence_pages="2-4", evidence_summary="Arc-melted samples were annealed at 1123 K for 30 min and water quenched; XRD/SEM report a single FCC phase.", record_mapping_status="all_records_direct"),
    18: dict(process_route="arc_melting+suction_casting", thermal_state_scope="as_cast", phase_class="composition_dependent_single_or_dual_fcc", product_form="suction_cast_rod", evidence_pages="2-5", evidence_summary="Arc-melted alloys were suction cast as 3 mm rods. The Cu-free alloy is single FCC, while Cu additions produce composition-dependent Cu-rich segregation and a second FCC phase.", record_mapping_status="composition_rule_required"),
    19: dict(process_route="arc_melting", thermal_state_scope="as_cast", phase_class="temperature_dependent_hexagonal_orthorhombic_coexistence", product_form="ingot", evidence_pages="2-5", evidence_summary="The as-cast alloy was arc melted. Temperature-dependent diffraction shows hexagonal/orthorhombic coexistence near room temperature, predominantly orthorhombic at 200 K and predominantly hexagonal above 320 K.", record_mapping_status="all_records_direct"),
    20: dict(process_route="magnetron_sputtering_mosaic_target+annealing", thermal_state_scope="deposited_300K_then_annealed_700K_60min_ArH2", phase_class="bcc_plus_fcc_after_annealing", product_form="thin_film", evidence_pages="2-5", evidence_summary="The Experimental section specifies magnetron sputtering from a mosaic target at 300 K followed by 700 K/60 min Ar-H2 annealing; the annealed film contains BCC and FCC contributions.", record_mapping_status="all_records_direct", target_audit_status="target_semantics_review_required", target_audit_note="The dataset value 295 K is reported in the source as the maximum of -Delta S_M, not explicitly as TC; the paper separately discusses a blocking temperature near 325 K."),
    21: dict(process_route="arc_melting", thermal_state_scope="as_cast", phase_class="two_ccp_solid_solutions_plus_sigma", product_form="ingot", evidence_pages="1-5", evidence_summary="The as-cast alloy was arc melted and is described as a three-phase system comprising a principal ccp solid solution, a Cu-rich ccp solid solution and a sigma intermetallic.", record_mapping_status="all_records_direct", target_audit_status="target_value_conflict_review_required", target_audit_note="The abstract reports 297 K, whereas the main text gives approximately 280 K; the same nominal composition is 329 K in reference 12."),
    22: dict(process_route="arc_melting+melt_spinning", thermal_state_scope="as_spun", phase_class="composition_dependent_amorphous_or_nanocrystalline", product_form="ribbon", evidence_pages="2-4", evidence_summary="Arc-melted ingots were melt spun. The Al-containing ribbon is fully amorphous; the Ni-containing ribbon is partly crystallized with HCP nanocrystals.", record_mapping_status="composition_rule_required"),
    23: dict(process_route="arc_melting+induction_melt_spinning", thermal_state_scope="as_spun", phase_class="single_phase_hcp", product_form="ribbon", evidence_pages="2-4", evidence_summary="Arc-melted master alloys were induction melt spun onto a Cu wheel at 29 m s-1; all three ribbons are single-phase HCP.", record_mapping_status="all_records_direct"),
    24: dict(process_route="arc_melting+state_specific_postprocessing", thermal_state_scope="as_cast_or_suction_cast_or_annealed_or_cold_deformed", phase_class="state_dependent_hcp_with_minor_fcc_or_oxide", product_form="ingot_or_rod", evidence_pages="2-5", evidence_summary="One master alloy was measured as cast, suction cast as a 3 mm rod, annealed at 1173 K for 2 h, or severely cold deformed. The four reported transition temperatures identify these states.", record_mapping_status="record_states_restored"),
    25: dict(process_route="arc_melting+vacuum_annealing+water_quenching", thermal_state_scope="annealed_1323K_9d_vacuum_water_quenched", phase_class="composition_dependent_LaFeSi13_multiphase", product_form="ingot", evidence_pages="2-5", evidence_summary="Arc-melted alloys were annealed at 1323 K for nine days under vacuum and water quenched. The Cr- and Co/Ni-containing samples retain secondary phases, while the quaternary-substituted alloy is predominantly La(Fe,Si)13.", record_mapping_status="composition_rule_required"),
    26: dict(process_route="arc_melting", thermal_state_scope="as_cast", phase_class="single_phase_orthorhombic_pnma", product_form="ingot", evidence_pages="2-4", evidence_summary="The alloy was arc melted under Ar and its diffraction pattern is indexed to the orthorhombic Pnma structure.", record_mapping_status="all_records_direct"),
    27: dict(process_route="torch_alloying+fluxing+J_quenching", thermal_state_scope="as_quenched", phase_class="amorphous", product_form="bulk_metallic_glass_rod", evidence_pages="1-2", evidence_summary="The alloy was torch-alloyed under Ar, fluxed for 4 h under vacuum, then J-quenched into rods; XRD confirms amorphous samples.", record_mapping_status="all_records_direct"),
    28: dict(process_route="arc_melting", thermal_state_scope="as_cast", phase_class="single_phase_hcp", product_form="ingot", evidence_pages="2", evidence_summary="The as-cast alloy was arc melted; XRD/Rietveld analysis identifies a homogeneous single-phase HCP structure.", record_mapping_status="all_records_direct"),
    29: dict(process_route="arc_melting+suction_casting", thermal_state_scope="as_quenched_or_annealed", phase_class="single_phase_bcc", product_form="suction_cast_rod", evidence_pages="2-4", evidence_summary="The source assigns 322 K to the as-quenched state and 334 K to the 700 K/1 h Ar-annealed state; both are BCC.", record_mapping_status="record_states_restored"),
    30: dict(process_route="arc_melting+melt_spinning", thermal_state_scope="as_spun", phase_class="single_phase_bcc", product_form="ribbon", evidence_pages="3-4", evidence_summary="The arc-melted ingot was remelted onto a Cu roller; XRD identifies the melt-spun alloy as a disordered BCC solid solution.", record_mapping_status="all_records_direct"),
    31: dict(process_route="arc_melting", thermal_state_scope="as_cast", phase_class="single_phase_hcp", product_form="ingot", evidence_pages="2", evidence_summary="The alloy was arc melted under Ar; room-temperature XRD identifies a single HCP phase.", record_mapping_status="all_records_direct"),
    32: dict(process_route="arc_melting", thermal_state_scope="as_cast", phase_class="dual_phase_bcc_fcc", product_form="ingot", evidence_pages="1-2", evidence_summary="Samples were made in an arc furnace under Ar; XRD shows a duplex BCC+FCC solid-solution structure.", record_mapping_status="all_records_direct"),
    33: dict(process_route="multiple_secondary_sources", thermal_state_scope="multiple_reported_states", phase_class="multiple_reported_phases", product_form="multiple", evidence_pages="entire review", evidence_summary="This is a review table aggregating records from multiple original publications; process, state and phase must be recovered from those primary sources rather than assigned at review level.", record_mapping_status="secondary_review_original_sources_required", target_audit_status="secondary_source_traceback_required", target_audit_note="Each record must be checked against its original primary publication before model-ready use."),
    34: dict(process_route="arc_melting+suction_casting", thermal_state_scope="as_quenched_or_annealed", phase_class="single_phase_bcc", product_form="suction_cast_sample", evidence_pages="1-4", evidence_summary="The source assigns 442 K to as-quenched and 462 K to 500 K/1 h Ar annealing with slow cooling; both states are BCC.", record_mapping_status="record_states_restored"),
    35: dict(process_route="arc_melting+casting+annealing+water_quenching", thermal_state_scope="annealed_1423K_10h_Ar_water_quenched", phase_class="composition_dependent_fcc_or_b2_bcc", product_form="cast_rod", evidence_pages="2-5", evidence_summary="Arc-melted alloys were cast as 6 mm rods, annealed at 1423 K for 10 h in Ar and water quenched. Al-free material is FCC; Al-containing alloys contain a B2 matrix and BCC Fe-Cr-rich precipitates.", record_mapping_status="composition_rule_required", target_audit_status="target_value_conflict_review_required", target_audit_note="The source reports multiple magnetic transitions for Al-containing compositions; the dataset's 685 K value does not match the source table's 640/905 K pair for x=1.0, and transition selection requires review."),
    36: dict(process_route="arc_melting", thermal_state_scope="as_cast", phase_class="single_phase_bcc", product_form="ingot", evidence_pages="2", evidence_summary="The alloy series was arc melted under Ar; XRD and microstructure analysis report a single BCC phase without observable secondary phases.", record_mapping_status="all_records_direct"),
    37: dict(process_route="arc_melting", thermal_state_scope="as_cast", phase_class="single_phase_orthorhombic_pnma", product_form="ingot", evidence_pages="2-3", evidence_summary="The two approximately 3 g ingots were arc melted under Ar with at least six remelts; Rietveld analysis identifies the orthorhombic Pnma structure and Table 1 reports TC=361 and 387 K.", record_mapping_status="all_records_direct"),
    38: dict(process_route="arc_melting", thermal_state_scope="as_cast", phase_class="single_phase_bcc", product_form="ingot", evidence_pages="2", evidence_summary="The alloy series was synthesized by arc melting; room-temperature XRD reports a single-phase BCC structure.", record_mapping_status="all_records_direct"),
    39: dict(process_route="arc_melting+copper_mold_casting", thermal_state_scope="as_cast", phase_class="amorphous", product_form="bulk_metallic_glass", evidence_pages="3-4", evidence_summary="Master alloys were arc melted and copper-mould cast into BMG samples; XRD shows broad humps without sharp peaks, indicating amorphous structures.", record_mapping_status="all_records_direct"),
    40: dict(process_route="arc_melting+cold_rolling+optional_annealing", thermal_state_scope="as_rolled_or_annealed_900C_1h_Ar", phase_class="fcc_with_state_dependent_strain_and_possible_oxide", product_form="cold_rolled_sheet", evidence_pages="2-4", evidence_summary="Arc-melted buttons were cold rolled to thin sheets and characterized both as rolled and after 900 C/1 h Ar annealing. Figure 1 reports separate TC series, but the dataset state assignment is not explicit.", record_mapping_status="state_series_mapping_required", target_audit_status="state_assignment_review_required", target_audit_note="The source plots separate as-rolled and annealed TC series; the dataset values do not unambiguously identify which state was transcribed."),
    41: dict(process_route="arc_melting+annealing+furnace_cooling", thermal_state_scope="annealed_800C_3h_furnace_cooled", phase_class="dual_phase_bcc_fcc", product_form="ingot_disc", evidence_pages="2-5", evidence_summary="Arc-melted ingots were annealed at 800 C for 3 h and furnace cooled for the magnetocaloric comparison; both selected compositions contain BCC and FCC phases.", record_mapping_status="all_records_direct", target_audit_status="target_semantics_review_required", target_audit_note="The dataset values 290 and 150 K are the source's peak magnetic-entropy-change temperatures/transition features, not uniformly established Curie temperatures."),
    42: dict(process_route="arc_melting", thermal_state_scope="as_cast", phase_class="composition_dependent_fcc_bcc", product_form="ingot", evidence_pages="3-4", evidence_summary="Arc-melted alloys transform with Al content from duplex FCC+BCC to single-phase BCC; figure-level phase fractions require composition-specific transcription.", record_mapping_status="figure_transcription_required"),
}


def main() -> None:
    manifest = pd.read_csv(MANIFEST)
    manifest["reference_number"] = manifest["reference_id"].str.extract(r"(\d+)").astype(int)
    rows = []
    for ref, annotation in ANNOTATIONS.items():
        source = manifest.loc[manifest["reference_number"].eq(ref)].iloc[0]
        doi_match = re.search(r"10\.\d{4,9}/[-._;()/:A-Z0-9]+", source.reference_text, re.I)
        annotation = {
            "target_audit_status": "verified_as_reported",
            "target_audit_note": "The source explicitly reports the tabulated value as a Curie or magnetic transition temperature consistent with the dataset label.",
            **annotation,
        }
        rows.append(
            {
                "reference_id": source.reference_id,
                "reference_number": ref,
                "doi": doi_match.group(0).rstrip(".") if doi_match else "",
                "n_unique_records": source.n_unique_records,
                **annotation,
                "verification_status": "verified_from_uploaded_full_text",
            }
        )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    table = pd.DataFrame(rows).sort_values("reference_number")
    table.to_csv(OUT, index=False)
    print(f"verified publications={len(table)}/42")
    print(f"covered unique records={table['n_unique_records'].sum()}/141")
    safe = table["record_mapping_status"].isin(["all_records_direct", "record_states_restored"])
    print(f"direct/restored mappings={int(safe.sum())}")
    print(f"target-review publications={int(table['target_audit_status'].ne('verified_as_reported').sum())}")
    print(OUT)


if __name__ == "__main__":
    main()
